version: '3.8'

services:
  app:
    image: ghcr.io/arkosaur/cloudflare-dns-dashboard:latest
    container_name: cloudflare-dns-dashboard
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      # 在下面的.env文件中设置这些变量
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID}
    env_file:
      - .env