version: '3.8'

services:
  backend:
    build: ./server
    container_name: dns-manager-backend
    command: sh -c "node tools/init-key.js && node src/server.js"
    environment:
      - NODE_ENV=production
    volumes:
      - sqlite_data:/app/database
      # Also mount the config to make it persistent
      - ./server/src/config:/app/src/config

  frontend:
    build: ./client
    container_name: dns-manager-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  sqlite_data:
