version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - PORT=3001
    env_file:
      - .env

  client:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:3001