name: Deploy

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy with Docker Compose
      run: |
        docker-compose up -d
        
    - name: Verify deployment
      run: |
        # Wait for services to start
        sleep 30
        
        # Check if services are running on correct ports
        curl -f http://localhost:3001/api/health || exit 1
        curl -f http://localhost:3000 || exit 1