name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install server dependencies
      run: |
        cd server
        npm install
        
    - name: Install client dependencies
      run: |
        cd client
        npm install
        
    - name: Run server tests
      run: |
        cd server
        npm test
        
    - name: Run client tests
      run: |
        cd client
        npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker images
      run: |
        docker build -t my-app-server ./server
        docker build -t my-app-client ./client
